### ISSUE TITLE
properties with underscore in the name are not transfered

### ISSUE THREAD

**Issue by semanticfire** [jimjonesbr/lod4wfs#29]
I've run into a problem where properties with underscores in their name do not get handled properly

If I have a sparql variable ?my_property it will end up in the WFS as 'property' with null value.

I've tested this on multiple datasets same result. I didn't have the time to check the problem in the code.

**Comment by jimjonesbr** [comment]
Hello @semanticfire I just submitted a quick fix to solve this issue. Could you tell me if it works for you?

**Comment by nicky508** [comment]
It works! However when I build the new version, I get this error:

Exception in thread "main" java.lang.NumberFormatException: null
        at java.lang.Integer.parseInt(Integer.java:542)
        at java.lang.Integer.parseInt(Integer.java:615)
        at de.ifgi.lod4wfs.core.GlobalSettings.refreshSystemVariables(GlobalSettings.java:265)
        at de.ifgi.lod4wfs.web.Start.main(Start.java:30)

This error is caused by a missing connectionTimeOut property in the config file.

**Comment by jimjonesbr** [comment]
I see. Does your settings file have a **connectionTimeOut** property? If so, can you please send me the config list shown on the application start up? Something like:

Application Version: 0.4.4 (Development Version)
Startup time: 13-09-2016 15:55:23
Java Runtime: 1.8.0_91
Operating System: Linux 4.2.0-42-generic (amd64)
Port: 8088
Default SPARQL Endpoint (SDA Features): http://linkeddata.uni-muenster.de:8081/parliament/sparql
Connection Time-out in ms: 1000
FDA Features Enabled: true
SDA Features Enabled: false
SOLR Features Enabled: false
FDA Features Directory: features/
Web Interface Preview Limit: 10

**Comment by nicky508** [comment]
Nope, it does not have it. I added it myself. Not sure, whether it disappeared because of my own actions. I see it is in the settings file on git. So maybe I was to fast. Just consider it fixed.

**Comment by jimjonesbr** [comment]
Great. Nice it works!

Set to closed.
